name: api-cinema

services:
  database:
    image: postgres:18.4-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ROOT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/