name: api-cinema

services:
  database:
    image: postgres:18.4-trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  
  api:
    image: postgrest/postgrest:v14.13
    ports:
      - "3000:3000"
    environment:
      - PGRST_DB_URI=postgrest://root:supermotdepasse@database.cinema