GET http://localhost:30000/pays

### filtre vertical
GET http://localhost:30000/pays?select=code2,nom

### filtre horizontal like F% % ecrit * dans l'url
GET http://localhost:30000/pays?code2=like.F*&select=code2,nom